# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeautifulSaid' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BeautifulSaid



pod 'AFNetworking'
pod 'DZNEmptyDataSet'
pod 'FLAnimatedImage'
pod 'SDWebImage'
pod 'YYKit'
pod 'Reachability'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'AsyncDisplayKit'
pod 'Masonry'
pod 'pop'
pod 'UITableView+FDTemplateLayoutCell_Bell'


end
